# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://testoapp.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_2d75dce292ac4a2eadc71b19e8c892c0 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_8f3162ced81e48aa8733d128fb561298 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: testoapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d75dce292ac4a2eadc71b19e8c892c0 }}/testoapp:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'testoapp'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad23ad35a5b44e4aabf1aefcb2b9e319 }}
            images: 'testoapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d75dce292ac4a2eadc71b19e8c892c0 }}/testoapp:${{ github.sha }}'